# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: weatherapi agent
      
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Weatherapi Docker Hub'
        repository: 'vahiniponnoju/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
- stage: Provision
  displayName: "Terraforming on Azure"
  dependsOn: Build
  jobs:
  - job: Provision
    displayName: "Provisioning container Instance"
    pool:
      name: weatherapi agent
    variables:
    - group: TerraformEnvVars
    steps:
    - script: |
        Remove-Item -Recurse -Force .terraform
        terraform init -reconfigure -input=false
        terraform validate
        terraform plan 
        terraform apply -auto-approve
      name: Runterraform  
      displayName: Run terraform
      env:
        ARM_Client_ID: $(ARM_Client_ID)
        ARM_Tenant_id: $(ARM_Tenant_id) 
        ARM_Client_secret: $(ARM_Client_secret)
        ARM_subscription_ID: $(ARM_subscription_ID)
